# Generated by Django 4.1.7 on 2023-04-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebSite', '0003_student_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studid',
            new_name='stuid',
        ),
    ]
